pipeline:
  publish_docker:
    image: plugins/docker
    repo: drone/drone
    dockerfile: Dockerfile.alpine
    secrets: [ docker_username, docker_password ]
    tag: [ drone-$${DRONE_BUILD_NUMBER} ]
    when:
      branch: master
      event: push
        #
        #  pytests:
        #    image: golang
        #    commands:
        #      - go get
        #      - go build
        #      - go test
        #
        #  frontend:
        #    image: node:6
        #    commands:
        #      - npm install
        #      - npm test
        #
        #  notify:
        #    image: plugins/slack
        #    channel: developers
        #    username: drone
