  pipeline:
    publish_docker:
      image: plugins/docker
      repo: ksiadz/devops-way
      secrets: [ docker_username, docker_password ]
      tags: 
      - build-${DRONE_BUILD_NUMBER}
      - commit-${DRONE_COMMIT_SHA}
      when:
        branch: master
        event: push
    
        
    pytest:
      image: ksiadz/devops-way:${DRONE_BUILD_NUMBER}
      commands:
        - make run-tests
      when:
        event: [ push ]
        
