  pipeline:
    pytest:
      image: python:3
      commands:
        - make run-tests
    when:
      event: [ push ]      
    
    publish_docker:
      image: plugins/docker
      repo: ksiadz/devops-way
      secrets: [ docker_username, docker_password ]
      tags: 
      - build-${DRONE_BUILD_NUMBER}
      - commit-${DRONE_COMMIT_SHA}
      when:
        branch: master
        event: push
        #
        #  pytests:
        #    image: golang
        #    commands:
        #      - go get
        #      - go build
        #      - go test
        #
        #  frontend:
        #    image: node:6
        #    commands:
        #      - npm install
        #      - npm test
        #
        #  notify:
        #    image: plugins/slack
        #    channel: developers
        #    username: drone
